# Generated by Django 5.2.8 on 2025-11-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturenote',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='lecturenote',
            name='user',
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='lecturenote',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
