# Generated by Django 5.2.8 on 2025-11-19 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturenote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecturenote',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicmastery',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
