# Generated by Django 5.2.8 on 2025-11-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
