# Generated by Django 5.2.8 on 2026-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_grade_userprofile_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturenote',
            name='formulas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='key_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='study_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
