# Generated by Django 5.2.8 on 2026-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_stickynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturenote',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
