# Generated by Django 5.2.8 on 2026-04-25 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_flashcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_caches', to='core.lecturenote')),
            ],
            options={
                'unique_together': {('lecture_note', 'action_type')},
            },
        ),
    ]
