# Generated by Django 5.2.8 on 2026-04-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_airesponsecache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickynote',
            options={'ordering': ['-is_pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='blooms_level',
            field=models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='is_high_yield',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('assertion_reason', 'Assertion-Reason')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='relevance_score',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='note_type',
            field=models.CharField(choices=[('lecture', 'Lecture Note'), ('hint', 'Hint'), ('exam', 'Exam Note'), ('formula', 'Formula')], default='lecture', max_length=20),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
