# Generated by Django 5.2.8 on 2026-04-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_stickynote_options_question_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airesponsecache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='airesponsecache',
            name='exam_syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_caches', to='core.examsyllabus'),
        ),
        migrations.AlterField(
            model_name='airesponsecache',
            name='lecture_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_caches', to='core.lecturenote'),
        ),
    ]
